const predictions = [
  "Une surprise de la part de votre époux viendra égayer cette heptade.",
  "Vous partagerez un moment de tendresse inattendu avec votre mari cette année.",
  "Une simple promenade avec votre époux ravivera votre connexion. Sortez le.",
  "Un projet que vous aviez abandonné avec votre époux reprendra forme.",
  "Une nouvelle activité à partager ensemble renforcera vos liens.",
  "Une soirée calme à deux sera source de réconfort cette année.",
  "Un moment d'humour partagé avec votre mari dissipera une tension.",
  "Votre mari vous aidera à retrouver votre confiance en vous dans les jours à venir.",
  "Une discussion profonde avec votre époux vous apportera des réponses.",
  "Une escapade à Dreadcast avec votre époux sera pleine de découvertes.",
  "Vous retrouverez de la sérénité en prenant du temps pour vous dans les jours à venir.",
  "Un nouveau loisir simple mais gratifiant égayera vos journées.",
  "Un livre inspirant viendra apaiser votre esprit. Ouvrez les EMs de l'UI.",
  "Un projet artistique redonnera un souffle nouveau à votre quotidien.",
  "Vous prendrez goût à un nouveau passe-temps qui vous procurera de la satisfaction.",
  "Une nouvelle routine apportera équilibre et sérénité dans votre quotidien.",
  "Vous découvrirez une nouvelle recette qui deviendra votre favorite. Moins que les douichs traingulaires, toutefois.",
  "Une sortie apaisera votre esprit et vous reconnectera à vous-même.",
  "Vous redécouvrirez le plaisir de cuisiner un plat qui vous rappelle de bons souvenirs.",
  "Une nouvelle habitude de bien-être apportera des changements positifs à votre mental.",
  "Vous savourerez bientôt un douich au fromage frais qui vous rappellera de bons souvenirs.",
  "Allez à la Plage.",
  "Un combat épique dans Dreadwow vous fera retrouver l'excitation d'un défi bien mené.",
  "Une alliance inattendue dans Dreadwow vous apportera une nouvelle perspective sur le jeu.",
  "Une quête à Dreadgate 3 vous emmènera plus loin que prévu, mais vous découvrirez de nouvelles possibilités.",
  "Une découverte fascinante dans Dreadgate 3 changera la manière dont vous abordez le jeu.",
  "Vous trouverez dans Dreadsims une nouvelle manière d'organiser votre monde qui vous apportera satisfaction.",
  "Un personnage dans Dreadsims reflétera une partie de vous que vous aviez oubliée.",
  "Un personnage dans Dreadsims sera aussi terrible que Jorem. prenez garde.",
  "Une nouvelle extension pour Dreadsims vous procurera des heures de plaisir créatif.",
  "Vous construirez dans Dreadsims une maison qui reflétera parfaitement votre esprit créatif.",
  "Une histoire que vous créez dans Dreadsims sera étonnamment touchante et inspirante... ou ressemblante.",
  "Une nouvelle opportunité de bénévolat à Dreadcast vous ouvrira à de nouvelles rencontres.",
  "Un projet communautaire à Dreadcast vous permettra de renouer avec des personnes inspirantes.",
  "Vous rencontrerez un ancien ami à Dreadcast, et cette rencontre réchauffera votre cœur.",
  "Vous découvrirez un lieu paisible à Dreadcast qui deviendra votre refuge personnel.",
  "Une discussion à Dreadcast vous apportera une nouvelle perspective sur une situation ancienne.",
  "Un évènement imprévu à Dreadcast vous apportera une nouvelle énergie créative.",
  "Vous renouerez avec une vieille passion qui vous apportera un sentiment d'accomplissement. Un nouveau sac de frappe ?",
  // "Vous ferez une rencontre inspirante dans les prochains jours qui influencera positivement vos projets.",
  "Un passe-temps que vous aviez négligé retrouvera sa place dans votre quotidien.",
  "Vous apprendrez une nouvelle compétence qui ajoutera de la valeur à vos journées.",
  "Un défi inattendu vous aidera à retrouver votre esprit combatif.",
  "Vous trouverez un moyen d'utiliser votre expérience pour aider les autres.",
  "Vous découvrirez une nouvelle série ou un livre qui vous captivera durant cette année.",
  "Vous recevrez une invitation surprenante qui apportera du changement à votre routine.",
  "Une expérience sensorielle (musique, art, plongée) vous apportera une profonde sérénité.",
  // "Vous renforcerez une amitié à travers une activité que vous aimez partager.",
  // "Vous atteindrez une réalisation personnelle qui apportera un sentiment de satisfaction durable.",
  // "Une vieille amitié reviendra dans votre vie, apportant soutien et réconfort.",
  // "Vous apporterez une aide précieuse à un proche qui traverse une période difficile.",
  // "Une conversation avec un ami vous apportera une solution à une question qui vous préoccupe.",
  "Vous recevrez un signe de l'univers qui vous guidera vers la bonne direction. TJP.",
  // "Une nouvelle opportunité d'apprentissage vous inspirera à explorer de nouvelles idées.",
  "Un souvenir joyeux vous rappellera la beauté des moments simples de la vie.",
  // "Vous réorganiserez votre espace de vie et cela vous apportera un sentiment de clarté.",
  // "Vous vous accorderez enfin le temps de vous détendre pleinement, sans culpabilité.",
  // "Une soirée calme à la maison sera plus satisfaisante que prévu.",
  "Vous ferez une découverte enrichissante lors d'une promenade.",
  // "Une opportunité de collaborer avec d'autres personnes créera un projet satisfaisant.",
  // "Vous trouverez un nouveau moyen de vous exprimer créativement.",
  "Vous reconnecterez avec une partie de vous-même que vous aviez mise de côté.",
  // "Vous ferez la rencontre d'une personne qui partagera vos intérêts et passions.",
  "Vous prendrez une décision importante qui changera votre quotidien de manière positive.",
  // "Une nouvelle activité physique apportera une amélioration à votre bien-être général.",
  // "Vous découvrirez une façon unique de surmonter les défis émotionnels que vous traversez.",
  // "Une période de réflexion apportera une solution à un problème persistant.",
  "Vous partagerez une nouvelle expérience avec un ami qui renforcera votre lien.",
  "Un message inattendu d'un proche vous apportera de la joie.",
  "Vous redécouvrirez un jeu ou une activité qui vous procurera un sentiment de légèreté.",
  // "Vous trouverez du réconfort dans une activité simple et quotidienne.",
  // "Vous ferez une rencontre clé qui vous ouvrira de nouvelles perspectives.",
  "Une amélioration de vos finances viendra soulager une pression que vous ressentiez.",
  "Vous découvrirez une nouvelle musique ou un film qui deviendra l'un de vos favoris.",
  // "Un nouveau rituel quotidien apportera structure et calme à votre routine.",
  // "Vous trouverez un moyen de contribuer à la communauté autour de vous qui vous apportera de la fierté.",
];

// Tableau des images associées aux prédictions
const predictionImages = [
  "img/image1.jpg",
  "img/image2.jpg",
  "img/image3.jpg",
  "img/image4.jpg",
  "img/image5.jpg",
  "img/image6.jpg",
  "img/image7.jpg",
  "img/image8.jpg",
  "img/image9.jpg",
  "img/image10.jpg",
  "img/image11.jpg",
  "img/image12.jpg",
  "img/image13.jpg",
  "img/image14.jpg",
  "img/image15.jpg",
  "img/image16.jpg",
  "img/image17.jpg",
  "img/image18.jpg",
  "img/image19.jpg",
  "img/image20.jpg",
  "img/image21.jpg",
  "img/image22.jpg",
  "img/image23.jpg",
  "img/image24.jpg",
  "img/image25.jpg",
  "img/image26.jpg",
  "img/image27.jpg",
  "img/image28.jpg",
  "img/image29.jpg",
  "img/image30.jpg",
  "img/image31.jpg",
  "img/image32.jpg",
  "img/image33.jpg",
  "img/image34.jpg",
  "img/image35.jpg",
  "img/image36.jpg",
  "img/image37.jpg",
  "img/image38.jpg",
  "img/image39.jpg",
  "img/image40.jpg",
  "img/image41.jpg",
  "img/image42.jpg",
  "img/image43.jpg",
  "img/image44.jpg",
  "img/image45.jpg",
  "img/image46.jpg",
  "img/image47.jpg",
  "img/image48.jpg",
  "img/image49.jpg",
  "img/image50.jpg",
  "img/image51.jpg",
  "img/image52.jpg",
  "img/image53.jpg",
  "img/image54.jpg",
  "img/image55.jpg",
  "img/image56.jpg",
  "img/image57.jpg",
  "img/image58.jpg",
  "img/image59.jpg",
  "img/image60.jpg",
  "img/image61.jpg",
  "img/image62.jpg",
  "img/image63.jpg",
  "img/image64.jpg",
  "img/image65.jpg",
  "img/image66.jpg",
  "img/image67.jpg",
  "img/image68.jpg",
  "img/image69.jpg",
  "img/image70.jpg",
  "img/image71.jpg",
  "img/image72.jpg",
  "img/image73.jpg",
  "img/image74.jpg",
  "img/image75.jpg",
  "img/image76.jpg",

  // !! Ajoute plus de chemins d'images ici !!
];

// Fonction pour retourner la carte
function flipCard() {
  const container = document.querySelector(".tarot-container");
  container.classList.toggle("flipped"); // Ajoute ou retire la classe flipped

  // Si la carte est retournée, générer une prédiction
  if (container.classList.contains("flipped")) {
    displayPrediction();
  } else {
    document.getElementById("prediction-text").innerText =
      "Cliquez sur la carte pour une prédiction";
    document.getElementById("prediction-image").src = ""; // Réinitialise l'image
  }
}

// Fonction pour afficher une prédiction aléatoire et son image associée
function displayPrediction() {
  const randomIndex = Math.floor(Math.random() * predictions.length);
  const predictionText = predictions[randomIndex];
  const predictionImage = predictionImages[randomIndex];

  document.getElementById("prediction-text").innerText = predictionText;
  document.getElementById("prediction-image").src = predictionImage; // Met à jour la source de l'image
}
